/* The following code was generated by JFlex 1.7.0 */

package syntax;

import tokens.*;
import java.util.ArrayList;

/**
    Lexer class to parse the input program into comprehensive 
    atom parts - tokens. 
**/

public final class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\2\1\5\1\4\1\0\1\5\1\3\16\2\4\0\1\5\1\0"+
    "\1\13\1\0\1\1\3\0\1\6\1\7\1\0\1\10\1\0\1\10"+
    "\1\12\1\0\12\11\7\0\32\1\1\0\1\14\2\0\1\1\1\0"+
    "\15\1\1\16\3\1\1\17\1\1\1\15\6\1\4\0\41\2\2\0"+
    "\4\1\4\0\1\1\2\0\1\2\7\0\1\1\4\0\1\1\5\0"+
    "\27\1\1\0\37\1\1\0\u01ca\1\4\0\14\1\16\0\5\1\7\0"+
    "\1\1\1\0\1\1\21\0\160\2\5\1\1\0\2\1\2\0\4\1"+
    "\1\0\1\1\6\0\1\1\1\0\3\1\1\0\1\1\1\0\24\1"+
    "\1\0\123\1\1\0\213\1\1\0\5\2\2\0\246\1\1\0\46\1"+
    "\2\0\1\1\7\0\47\1\7\0\1\1\1\0\55\2\1\0\1\2"+
    "\1\0\2\2\1\0\2\2\1\0\1\2\10\0\33\1\5\0\3\1"+
    "\15\0\6\2\5\0\1\1\4\0\13\2\1\0\1\2\3\0\53\1"+
    "\25\2\12\11\4\0\2\1\1\2\143\1\1\0\1\1\10\2\1\0"+
    "\6\2\2\1\2\2\1\0\4\2\2\1\12\11\3\1\2\0\1\1"+
    "\17\0\1\2\1\1\1\2\36\1\33\2\2\0\131\1\13\2\1\1"+
    "\16\0\12\11\41\1\11\2\2\1\4\0\1\1\5\0\26\1\4\2"+
    "\1\1\11\2\1\1\3\2\1\1\5\2\22\0\31\1\3\2\4\0"+
    "\13\1\65\0\25\1\1\0\10\1\26\0\60\2\66\1\3\2\1\1"+
    "\22\2\1\1\7\2\12\1\2\2\2\0\12\11\1\0\20\1\3\2"+
    "\1\0\10\1\2\0\2\1\2\0\26\1\1\0\7\1\1\0\1\1"+
    "\3\0\4\1\2\0\1\2\1\1\7\2\2\0\2\2\2\0\3\2"+
    "\1\1\10\0\1\2\4\0\2\1\1\0\3\1\2\2\2\0\12\11"+
    "\4\1\7\0\2\1\4\0\3\2\1\0\6\1\4\0\2\1\2\0"+
    "\26\1\1\0\7\1\1\0\2\1\1\0\2\1\1\0\2\1\2\0"+
    "\1\2\1\0\5\2\4\0\2\2\2\0\3\2\3\0\1\2\7\0"+
    "\4\1\1\0\1\1\7\0\12\11\2\2\3\1\1\2\13\0\3\2"+
    "\1\0\11\1\1\0\3\1\1\0\26\1\1\0\7\1\1\0\2\1"+
    "\1\0\5\1\2\0\1\2\1\1\10\2\1\0\3\2\1\0\3\2"+
    "\2\0\1\1\17\0\2\1\2\2\2\0\12\11\1\0\1\1\7\0"+
    "\1\1\6\2\1\0\3\2\1\0\10\1\2\0\2\1\2\0\26\1"+
    "\1\0\7\1\1\0\2\1\1\0\5\1\2\0\1\2\1\1\7\2"+
    "\2\0\2\2\2\0\3\2\10\0\2\2\4\0\2\1\1\0\3\1"+
    "\2\2\2\0\12\11\1\0\1\1\20\0\1\2\1\1\1\0\6\1"+
    "\3\0\3\1\1\0\4\1\3\0\2\1\1\0\1\1\1\0\2\1"+
    "\3\0\2\1\3\0\3\1\3\0\14\1\4\0\5\2\3\0\3\2"+
    "\1\0\4\2\2\0\1\1\6\0\1\2\16\0\12\11\11\0\1\1"+
    "\6\0\4\2\1\0\10\1\1\0\3\1\1\0\27\1\1\0\20\1"+
    "\3\0\1\1\7\2\1\0\3\2\1\0\4\2\7\0\2\2\1\0"+
    "\3\1\5\0\2\1\2\2\2\0\12\11\20\0\1\1\3\2\1\0"+
    "\10\1\1\0\3\1\1\0\27\1\1\0\12\1\1\0\5\1\2\0"+
    "\1\2\1\1\7\2\1\0\3\2\1\0\4\2\7\0\2\2\7\0"+
    "\1\1\1\0\2\1\2\2\2\0\12\11\1\0\2\1\15\0\4\2"+
    "\1\0\10\1\1\0\3\1\1\0\51\1\2\2\1\1\7\2\1\0"+
    "\3\2\1\0\4\2\1\1\5\0\3\1\1\2\7\0\3\1\2\2"+
    "\2\0\12\11\12\0\6\1\2\0\2\2\1\0\22\1\3\0\30\1"+
    "\1\0\11\1\1\0\1\1\2\0\7\1\3\0\1\2\4\0\6\2"+
    "\1\0\1\2\1\0\10\2\6\0\12\11\2\0\2\2\15\0\60\1"+
    "\1\2\2\1\7\2\4\0\10\1\10\2\1\0\12\11\47\0\2\1"+
    "\1\0\1\1\2\0\2\1\1\0\1\1\2\0\1\1\6\0\4\1"+
    "\1\0\7\1\1\0\3\1\1\0\1\1\1\0\1\1\2\0\2\1"+
    "\1\0\4\1\1\2\2\1\6\2\1\0\2\2\1\1\2\0\5\1"+
    "\1\0\1\1\1\0\6\2\2\0\12\11\2\0\4\1\40\0\1\1"+
    "\27\0\2\2\6\0\12\11\13\0\1\2\1\0\1\2\1\0\1\2"+
    "\4\0\2\2\10\1\1\0\44\1\4\0\24\2\1\0\2\2\5\1"+
    "\13\2\1\0\44\2\11\0\1\2\71\0\53\1\24\2\1\1\12\11"+
    "\6\0\6\1\4\2\4\1\3\2\1\1\3\2\2\1\7\2\3\1"+
    "\4\2\15\1\14\2\1\1\1\2\12\11\4\2\2\0\46\1\1\0"+
    "\1\1\5\0\1\1\2\0\53\1\1\0\u014d\1\1\0\4\1\2\0"+
    "\7\1\1\0\1\1\1\0\4\1\2\0\51\1\1\0\4\1\2\0"+
    "\41\1\1\0\4\1\2\0\7\1\1\0\1\1\1\0\4\1\2\0"+
    "\17\1\1\0\71\1\1\0\4\1\2\0\103\1\2\0\3\2\40\0"+
    "\20\1\20\0\126\1\2\0\6\1\3\0\u026c\1\2\0\21\1\1\0"+
    "\32\1\5\0\113\1\3\0\13\1\7\0\15\1\1\0\4\1\3\2"+
    "\13\0\22\1\3\2\13\0\22\1\2\2\14\0\15\1\1\0\3\1"+
    "\1\0\2\2\14\0\64\1\40\2\3\0\1\1\3\0\2\1\1\2"+
    "\2\0\12\11\41\0\4\2\1\0\12\11\6\0\130\1\10\0\5\1"+
    "\2\2\42\1\1\2\1\1\5\0\106\1\12\0\37\1\1\0\14\2"+
    "\4\0\14\2\12\0\12\11\36\1\2\0\5\1\13\0\54\1\4\0"+
    "\32\1\6\0\12\11\46\0\27\1\5\2\4\0\65\1\12\2\1\0"+
    "\35\2\2\0\1\2\12\11\6\0\12\11\15\0\1\1\10\0\16\2"+
    "\102\0\5\2\57\1\21\2\7\1\4\0\12\11\21\0\11\2\14\0"+
    "\3\2\36\1\15\2\2\1\12\11\54\1\16\2\14\0\44\1\24\2"+
    "\10\0\12\11\3\0\3\1\12\11\44\1\2\0\11\1\107\0\3\2"+
    "\1\0\25\2\4\1\1\2\4\1\3\2\2\1\3\2\6\0\300\1"+
    "\72\2\1\0\5\2\u0116\1\2\0\6\1\2\0\46\1\2\0\6\1"+
    "\2\0\10\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0\37\1"+
    "\2\0\65\1\1\0\7\1\1\0\1\1\3\0\3\1\1\0\7\1"+
    "\3\0\4\1\2\0\6\1\4\0\15\1\5\0\3\1\1\0\7\1"+
    "\16\0\5\2\32\0\5\2\20\0\2\1\23\0\1\1\13\0\5\2"+
    "\1\0\12\2\1\0\1\1\15\0\1\1\20\0\15\1\3\0\40\1"+
    "\20\0\15\2\4\0\1\2\3\0\14\2\21\0\1\1\4\0\1\1"+
    "\2\0\12\1\1\0\1\1\3\0\5\1\6\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\4\1\1\0\13\1\2\0\4\1\5\0\5\1"+
    "\4\0\1\1\21\0\51\1\u0a77\0\57\1\1\0\57\1\1\0\205\1"+
    "\6\0\4\1\3\2\2\1\14\0\46\1\1\0\1\1\5\0\1\1"+
    "\2\0\70\1\7\0\1\1\17\0\1\2\27\1\11\0\7\1\1\0"+
    "\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0"+
    "\7\1\1\0\7\1\1\0\40\2\57\0\1\1\u01d5\0\3\1\31\0"+
    "\11\1\6\2\1\0\5\1\2\0\5\1\4\0\126\1\2\0\2\2"+
    "\2\0\3\1\1\0\132\1\1\0\4\1\5\0\52\1\2\0\136\1"+
    "\21\0\33\1\65\0\20\1\u0200\0\u19b6\1\112\0\u51eb\1\25\0\u048d\1"+
    "\103\0\56\1\2\0\u010d\1\3\0\20\1\12\11\2\1\24\0\57\1"+
    "\1\2\4\0\12\2\1\0\37\1\2\2\120\1\2\2\45\0\11\1"+
    "\2\0\147\1\2\0\44\1\1\0\10\1\77\0\13\1\1\2\3\1"+
    "\1\2\4\1\1\2\27\1\5\2\20\0\1\1\7\0\64\1\14\0"+
    "\2\2\62\1\22\2\12\0\12\11\6\0\22\2\6\1\3\0\1\1"+
    "\1\0\1\1\2\0\12\11\34\1\10\2\2\0\27\1\15\2\14\0"+
    "\35\1\3\0\4\2\57\1\16\2\16\0\1\1\12\11\6\0\5\1"+
    "\1\2\12\1\12\11\5\1\1\0\51\1\16\2\11\0\3\1\1\2"+
    "\10\1\2\2\2\0\12\11\6\0\27\1\3\0\1\1\3\2\62\1"+
    "\1\2\1\1\3\2\2\1\2\2\5\1\2\2\1\1\1\2\1\1"+
    "\30\0\3\1\2\0\13\1\5\2\2\0\3\1\2\2\12\0\6\1"+
    "\2\0\6\1\2\0\6\1\11\0\7\1\1\0\7\1\1\0\53\1"+
    "\1\0\12\1\12\0\163\1\10\2\1\0\2\2\2\0\12\11\6\0"+
    "\u2ba4\1\14\0\27\1\4\0\61\1\u2104\0\u016e\1\2\0\152\1\46\0"+
    "\7\1\14\0\5\1\5\0\1\1\1\2\12\1\1\0\15\1\1\0"+
    "\5\1\1\0\1\1\1\0\2\1\1\0\2\1\1\0\154\1\41\0"+
    "\u016b\1\22\0\100\1\2\0\66\1\50\0\15\1\3\0\20\2\20\0"+
    "\20\2\3\0\2\1\30\0\3\1\31\0\1\1\6\0\5\1\1\0"+
    "\207\1\2\0\1\2\4\0\1\1\13\0\12\11\7\0\32\1\4\0"+
    "\1\1\1\0\32\1\13\0\131\1\3\0\6\1\2\0\6\1\2\0"+
    "\6\1\2\0\3\1\3\0\2\1\3\0\2\1\22\0\3\2\4\0"+
    "\14\1\1\0\32\1\1\0\23\1\1\0\2\1\1\0\17\1\2\0"+
    "\16\1\42\0\173\1\105\0\65\1\210\0\1\2\202\0\35\1\3\0"+
    "\61\1\17\0\1\2\37\0\40\1\15\0\36\1\5\0\46\1\5\2"+
    "\5\0\36\1\2\0\44\1\4\0\10\1\1\0\5\1\52\0\236\1"+
    "\2\0\12\11\6\0\44\1\4\0\44\1\4\0\50\1\10\0\64\1"+
    "\234\0\u0137\1\11\0\26\1\12\0\10\1\230\0\6\1\2\0\1\1"+
    "\1\0\54\1\1\0\2\1\3\0\1\1\2\0\27\1\12\0\27\1"+
    "\11\0\37\1\101\0\23\1\1\0\2\1\12\0\26\1\12\0\32\1"+
    "\106\0\70\1\6\0\2\1\100\0\1\1\3\2\1\0\2\2\5\0"+
    "\4\2\4\1\1\0\3\1\1\0\33\1\4\0\3\2\4\0\1\2"+
    "\40\0\35\1\3\0\35\1\43\0\10\1\1\0\34\1\2\2\31\0"+
    "\66\1\12\0\26\1\12\0\23\1\15\0\22\1\156\0\111\1\67\0"+
    "\63\1\15\0\63\1\u030d\0\3\2\65\1\17\2\37\0\12\11\17\0"+
    "\4\2\55\1\13\2\2\0\1\2\22\0\31\1\7\0\12\11\6\0"+
    "\3\2\44\1\16\2\1\0\12\11\20\0\43\1\1\2\2\0\1\1"+
    "\11\0\3\2\60\1\16\2\4\1\5\0\3\2\3\0\12\11\1\1"+
    "\1\0\1\1\43\0\22\1\1\0\31\1\14\2\6\0\1\2\101\0"+
    "\7\1\1\0\1\1\1\0\4\1\1\0\17\1\1\0\12\1\7\0"+
    "\57\1\14\2\5\0\12\11\6\0\4\2\1\0\10\1\2\0\2\1"+
    "\2\0\26\1\1\0\7\1\1\0\2\1\1\0\5\1\2\0\1\2"+
    "\1\1\7\2\2\0\2\2\2\0\3\2\2\0\1\1\6\0\1\2"+
    "\5\0\5\1\2\2\2\0\7\2\3\0\5\2\213\0\65\1\22\2"+
    "\4\1\5\0\12\11\46\0\60\1\24\2\2\1\1\0\1\1\10\0"+
    "\12\11\246\0\57\1\7\2\2\0\11\2\27\0\4\1\2\2\42\0"+
    "\60\1\21\2\3\0\1\1\13\0\12\11\46\0\53\1\15\2\10\0"+
    "\12\11\66\0\32\1\3\0\17\2\4\0\12\11\u0166\0\100\1\12\11"+
    "\25\0\1\1\u0100\0\1\1\12\2\50\1\7\2\1\1\4\2\10\0"+
    "\1\2\10\0\1\1\13\2\50\1\2\0\4\1\20\2\46\0\71\1"+
    "\u0107\0\11\1\1\0\45\1\10\2\1\0\10\2\1\1\17\0\12\11"+
    "\30\0\36\1\2\0\26\2\1\0\16\2\111\0\7\1\1\0\2\1"+
    "\1\0\46\1\6\2\3\0\1\2\1\0\2\2\1\0\7\2\1\1"+
    "\1\2\10\0\12\2\u02a6\0\u039a\1\146\0\157\1\21\0\304\1\u0abc\0"+
    "\u042f\1\u0fd1\0\u0247\1\u21b9\0\u0239\1\7\0\37\1\1\0\12\11\146\0"+
    "\36\1\2\0\5\2\13\0\60\1\7\2\11\0\4\1\14\0\12\11"+
    "\11\0\25\1\5\0\23\1\u0370\0\105\1\13\0\1\1\56\2\20\0"+
    "\4\2\15\1\100\0\2\1\36\0\u17ed\1\23\0\u02f3\1\u250d\0\u011f\1"+
    "\121\0\u018c\1\u0904\0\153\1\5\0\15\1\3\0\11\1\7\0\12\1"+
    "\3\0\2\2\1\0\4\2\u14c1\0\5\2\3\0\26\2\2\0\7\2"+
    "\36\0\4\2\224\0\3\2\u01bb\0\125\1\1\0\107\1\1\0\2\1"+
    "\2\0\1\1\2\0\2\1\2\0\4\1\1\0\14\1\1\0\1\1"+
    "\1\0\7\1\1\0\101\1\1\0\4\1\2\0\10\1\1\0\7\1"+
    "\1\0\34\1\1\0\4\1\1\0\5\1\1\0\1\1\3\0\7\1"+
    "\1\0\u0154\1\2\0\31\1\1\0\31\1\1\0\37\1\1\0\31\1"+
    "\1\0\37\1\1\0\31\1\1\0\37\1\1\0\31\1\1\0\37\1"+
    "\1\0\31\1\1\0\10\1\2\0\62\11\u0200\0\67\2\4\0\62\2"+
    "\10\0\1\2\16\0\1\2\26\0\5\2\1\0\17\2\u0550\0\7\2"+
    "\1\0\21\2\2\0\7\2\1\0\2\2\1\0\5\2\u07d5\0\305\1"+
    "\13\0\7\2\51\0\104\1\7\2\5\0\12\11\u04a6\0\4\1\1\0"+
    "\33\1\1\0\2\1\1\0\1\1\2\0\1\1\1\0\12\1\1\0"+
    "\4\1\1\0\1\1\1\0\1\1\6\0\1\1\4\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\3\1\1\0\2\1\1\0\1\1\2\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\2\0\4\1\1\0\7\1\1\0\4\1\1\0"+
    "\4\1\1\0\1\1\1\0\12\1\1\0\21\1\5\0\3\1\1\0"+
    "\5\1\1\0\21\1\u1144\0\ua6d7\1\51\0\u1035\1\13\0\336\1\2\0"+
    "\u1682\1\16\0\u1d31\1\u0c1f\0\u021e\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\2\36\0\140\2\200\0\360\2\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\0\1\11\1\0\1\12\1\13\1\14\1\15"+
    "\1\16\1\11";

  private static int [] zzUnpackAction() {
    int [] result = new int[20];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\20\0\40\0\60\0\100\0\120\0\120\0\120"+
    "\0\140\0\40\0\160\0\200\0\200\0\220\0\40\0\40"+
    "\0\40\0\40\0\40\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[20];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\2\6\1\7\1\10\5\3"+
    "\3\4\3\11\2\3\6\11\1\12\1\13\3\11\21\0"+
    "\2\4\6\0\1\4\3\0\3\4\4\0\1\6\3\0"+
    "\1\14\1\15\1\16\1\17\14\0\1\14\1\15\1\16"+
    "\1\17\4\0\3\11\2\0\6\11\2\0\3\11\13\0"+
    "\1\20\1\0\1\21\1\22\1\23\11\0\1\15\1\16"+
    "\16\0\1\24\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\6\1\1\11\1\1\1\0\1\1\1\0"+
    "\5\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[20];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer stringLiteralBuffer = new StringBuffer();

    private Token capture(Token token) {
        return token;
    }

    private void expandLiteral(String text) {
        stringLiteralBuffer.append(text);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3390) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // ` translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Unexpected character <"+yytext()+">");
            } 
            // fall through
          case 15: break;
          case 2: 
            { return capture(new Identifier(yytext()));
            } 
            // fall through
          case 16: break;
          case 3: 
            { /* Skip */
            } 
            // fall through
          case 17: break;
          case 4: 
            { return capture(new LeftBracket());
            } 
            // fall through
          case 18: break;
          case 5: 
            { return capture(new RightBracket());
            } 
            // fall through
          case 19: break;
          case 6: 
            { stringLiteralBuffer.append(yytext());
            } 
            // fall through
          case 20: break;
          case 7: 
            { yybegin(YYINITIAL); return capture(new Literal(stringLiteralBuffer.toString()));
            } 
            // fall through
          case 21: break;
          case 8: 
            { stringLiteralBuffer.append('\\');
            } 
            // fall through
          case 22: break;
          case 9: 
            { return capture(new Literal(yytext().trim()));
            } 
            // fall through
          case 23: break;
          case 10: 
            { stringLiteralBuffer.setLength(0); yybegin(STRING);
            } 
            // fall through
          case 24: break;
          case 11: 
            { stringLiteralBuffer.append('"');
            } 
            // fall through
          case 25: break;
          case 12: 
            { stringLiteralBuffer.append('\t');
            } 
            // fall through
          case 26: break;
          case 13: 
            { stringLiteralBuffer.append('\n');
            } 
            // fall through
          case 27: break;
          case 14: 
            { stringLiteralBuffer.append('\r');
            } 
            // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
